- name: Setup MediaWiki Web Server
  hosts: web
  vars:
    db_server_ip: "34.202.166.214"
    db_user: "mediawikiuser"
    db_password: "your_secure_password"
    web_server_name: "http1"
    site_name: "MyWiki"
  roles:
    - web

- name: Setup MariaDB Database Server
  hosts: db
  roles:
    - db
