- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow MySQL port 3306
  ufw:
    rule: allow
    port: 3306
    proto: tcp

- name: Enable UFW firewall
  ufw:
    state: enabled
    
- name: Install MariaDB
  apt:
    name: mariadb-server
    state: present
    update_cache: yes

- name: Enable and start MariaDB
  systemd:
    name: mariadb
    enabled: yes
    state: started
