- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow HTTP port 80
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Enable UFW firewall
  ufw:
    state: enabled

- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Enable and start Apache
  systemd:
    name: apache2
    enabled: yes
    state: started

- name: Set up Apache config for MediaWiki
  copy:
    dest: /etc/apache2/sites-available/mediawiki.conf
    content: |
      <VirtualHost *:80>
          ServerName http1
          DocumentRoot /var/www/html/mediawiki

          <Directory /var/www/html/mediawiki>
              Options FollowSymLinks
              AllowOverride All
              Require all granted
          </Directory>

          ErrorLog ${APACHE_LOG_DIR}/mediawiki_error.log
          CustomLog ${APACHE_LOG_DIR}/mediawiki_access.log combined
      </VirtualHost>

- name: Enable mediawiki site
  command: a2ensite mediawiki.conf
  notify: Restart Apache
  args:
    creates: /etc/apache2/sites-enabled/mediawiki.conf

- name: Enable rewrite module (required by MediaWiki)
  command: a2enmod rewrite
  notify: Restart Apache

