- name: Download MediaWiki
  get_url:
    url: https://releases.wikimedia.org/mediawiki/1.43/mediawiki-1.43.1.tar.gz
    dest: /tmp/mediawiki.tar.gz

- name: Extract MediaWiki
  unarchive:
    src: /tmp/mediawiki.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Rename MediaWiki directory
  command: mv /var/www/html/mediawiki-1.43.1 /var/www/html/mediawiki
  args:
    creates: /var/www/html/mediawiki

- name: Set permissions
  file:
    path: /var/www/html/mediawiki
    owner: www-data
    group: www-data
    recurse: yes

- name: Deploy LocalSettings.php from template
  template:
    src: LocalSettings.php.j2
    dest: /var/www/html/mediawiki/LocalSettings.php
    owner: www-data
    group: www-data
    mode: '0644'
